namespace AstroDeepak.Views
{
    public class CountryCodeOption
    {
        public string CountryName { get; set; } = string.Empty;
        public string DialCode { get; set; } = string.Empty; // e.g. "+91"
        public string Display => $"{CountryName} ({DialCode})";
    }

    public static class CountryCodes
    {
        public static readonly List<CountryCodeOption> All = new()
        {
            new() { CountryName = "Afghanistan", DialCode = "+93" },
            new() { CountryName = "Albania", DialCode = "+355" },
            new() { CountryName = "Algeria", DialCode = "+213" },
            new() { CountryName = "Andorra", DialCode = "+376" },
            new() { CountryName = "Angola", DialCode = "+244" },
            new() { CountryName = "Argentina", DialCode = "+54" },
            new() { CountryName = "Armenia", DialCode = "+374" },
            new() { CountryName = "Australia", DialCode = "+61" },
            new() { CountryName = "Austria", DialCode = "+43" },
            new() { CountryName = "Azerbaijan", DialCode = "+994" },
            new() { CountryName = "Bahamas", DialCode = "+1242" },
            new() { CountryName = "Bahrain", DialCode = "+973" },
            new() { CountryName = "Bangladesh", DialCode = "+880" },
            new() { CountryName = "Belarus", DialCode = "+375" },
            new() { CountryName = "Belgium", DialCode = "+32" },
            new() { CountryName = "Belize", DialCode = "+501" },
            new() { CountryName = "Bhutan", DialCode = "+975" },
            new() { CountryName = "Bolivia", DialCode = "+591" },
            new() { CountryName = "Bosnia and Herzegovina", DialCode = "+387" },
            new() { CountryName = "Brazil", DialCode = "+55" },
            new() { CountryName = "Brunei", DialCode = "+673" },
            new() { CountryName = "Bulgaria", DialCode = "+359" },
            new() { CountryName = "Cambodia", DialCode = "+855" },
            new() { CountryName = "Cameroon", DialCode = "+237" },
            new() { CountryName = "Canada", DialCode = "+1" },
            new() { CountryName = "Chile", DialCode = "+56" },
            new() { CountryName = "China", DialCode = "+86" },
            new() { CountryName = "Colombia", DialCode = "+57" },
            new() { CountryName = "Costa Rica", DialCode = "+506" },
            new() { CountryName = "Croatia", DialCode = "+385" },
            new() { CountryName = "Cuba", DialCode = "+53" },
            new() { CountryName = "Cyprus", DialCode = "+357" },
            new() { CountryName = "Czech Republic", DialCode = "+420" },
            new() { CountryName = "Denmark", DialCode = "+45" },
            new() { CountryName = "Dominican Republic", DialCode = "+1809" },
            new() { CountryName = "Ecuador", DialCode = "+593" },
            new() { CountryName = "Egypt", DialCode = "+20" },
            new() { CountryName = "El Salvador", DialCode = "+503" },
            new() { CountryName = "Estonia", DialCode = "+372" },
            new() { CountryName = "Ethiopia", DialCode = "+251" },
            new() { CountryName = "Fiji", DialCode = "+679" },
            new() { CountryName = "Finland", DialCode = "+358" },
            new() { CountryName = "France", DialCode = "+33" },
            new() { CountryName = "Georgia", DialCode = "+995" },
            new() { CountryName = "Germany", DialCode = "+49" },
            new() { CountryName = "Ghana", DialCode = "+233" },
            new() { CountryName = "Greece", DialCode = "+30" },
            new() { CountryName = "Guatemala", DialCode = "+502" },
            new() { CountryName = "Honduras", DialCode = "+504" },
            new() { CountryName = "Hong Kong", DialCode = "+852" },
            new() { CountryName = "Hungary", DialCode = "+36" },
            new() { CountryName = "Iceland", DialCode = "+354" },
            new() { CountryName = "India", DialCode = "+91" },
            new() { CountryName = "Indonesia", DialCode = "+62" },
            new() { CountryName = "Iran", DialCode = "+98" },
            new() { CountryName = "Iraq", DialCode = "+964" },
            new() { CountryName = "Ireland", DialCode = "+353" },
            new() { CountryName = "Israel", DialCode = "+972" },
            new() { CountryName = "Italy", DialCode = "+39" },
            new() { CountryName = "Jamaica", DialCode = "+1876" },
            new() { CountryName = "Japan", DialCode = "+81" },
            new() { CountryName = "Jordan", DialCode = "+962" },
            new() { CountryName = "Kazakhstan", DialCode = "+7" },
            new() { CountryName = "Kenya", DialCode = "+254" },
            new() { CountryName = "Kuwait", DialCode = "+965" },
            new() { CountryName = "Kyrgyzstan", DialCode = "+996" },
            new() { CountryName = "Laos", DialCode = "+856" },
            new() { CountryName = "Latvia", DialCode = "+371" },
            new() { CountryName = "Lebanon", DialCode = "+961" },
            new() { CountryName = "Libya", DialCode = "+218" },
            new() { CountryName = "Liechtenstein", DialCode = "+423" },
            new() { CountryName = "Lithuania", DialCode = "+370" },
            new() { CountryName = "Luxembourg", DialCode = "+352" },
            new() { CountryName = "Macau", DialCode = "+853" },
            new() { CountryName = "Malaysia", DialCode = "+60" },
            new() { CountryName = "Maldives", DialCode = "+960" },
            new() { CountryName = "Malta", DialCode = "+356" },
            new() { CountryName = "Mauritius", DialCode = "+230" },
            new() { CountryName = "Mexico", DialCode = "+52" },
            new() { CountryName = "Moldova", DialCode = "+373" },
            new() { CountryName = "Monaco", DialCode = "+377" },
            new() { CountryName = "Mongolia", DialCode = "+976" },
            new() { CountryName = "Montenegro", DialCode = "+382" },
            new() { CountryName = "Morocco", DialCode = "+212" },
            new() { CountryName = "Myanmar", DialCode = "+95" },
            new() { CountryName = "Nepal", DialCode = "+977" },
            new() { CountryName = "Netherlands", DialCode = "+31" },
            new() { CountryName = "New Zealand", DialCode = "+64" },
            new() { CountryName = "Nicaragua", DialCode = "+505" },
            new() { CountryName = "Nigeria", DialCode = "+234" },
            new() { CountryName = "North Korea", DialCode = "+850" },
            new() { CountryName = "North Macedonia", DialCode = "+389" },
            new() { CountryName = "Norway", DialCode = "+47" },
            new() { CountryName = "Oman", DialCode = "+968" },
            new() { CountryName = "Pakistan", DialCode = "+92" },
            new() { CountryName = "Panama", DialCode = "+507" },
            new() { CountryName = "Papua New Guinea", DialCode = "+675" },
            new() { CountryName = "Paraguay", DialCode = "+595" },
            new() { CountryName = "Peru", DialCode = "+51" },
            new() { CountryName = "Philippines", DialCode = "+63" },
            new() { CountryName = "Poland", DialCode = "+48" },
            new() { CountryName = "Portugal", DialCode = "+351" },
            new() { CountryName = "Qatar", DialCode = "+974" },
            new() { CountryName = "Romania", DialCode = "+40" },
            new() { CountryName = "Russia", DialCode = "+7" },
            new() { CountryName = "Rwanda", DialCode = "+250" },
            new() { CountryName = "Saudi Arabia", DialCode = "+966" },
            new() { CountryName = "Serbia", DialCode = "+381" },
            new() { CountryName = "Singapore", DialCode = "+65" },
            new() { CountryName = "Slovakia", DialCode = "+421" },
            new() { CountryName = "Slovenia", DialCode = "+386" },
            new() { CountryName = "South Africa", DialCode = "+27" },
            new() { CountryName = "South Korea", DialCode = "+82" },
            new() { CountryName = "Spain", DialCode = "+34" },
            new() { CountryName = "Sri Lanka", DialCode = "+94" },
            new() { CountryName = "Sudan", DialCode = "+249" },
            new() { CountryName = "Sweden", DialCode = "+46" },
            new() { CountryName = "Switzerland", DialCode = "+41" },
            new() { CountryName = "Syria", DialCode = "+963" },
            new() { CountryName = "Taiwan", DialCode = "+886" },
            new() { CountryName = "Tajikistan", DialCode = "+992" },
            new() { CountryName = "Tanzania", DialCode = "+255" },
            new() { CountryName = "Thailand", DialCode = "+66" },
            new() { CountryName = "Tunisia", DialCode = "+216" },
            new() { CountryName = "Turkey", DialCode = "+90" },
            new() { CountryName = "Turkmenistan", DialCode = "+993" },
            new() { CountryName = "Uganda", DialCode = "+256" },
            new() { CountryName = "Ukraine", DialCode = "+380" },
            new() { CountryName = "United Arab Emirates", DialCode = "+971" },
            new() { CountryName = "United Kingdom", DialCode = "+44" },
            new() { CountryName = "United States", DialCode = "+1" },
            new() { CountryName = "Uruguay", DialCode = "+598" },
            new() { CountryName = "Uzbekistan", DialCode = "+998" },
            new() { CountryName = "Venezuela", DialCode = "+58" },
            new() { CountryName = "Vietnam", DialCode = "+84" },
            new() { CountryName = "Yemen", DialCode = "+967" },
            new() { CountryName = "Zambia", DialCode = "+260" },
            new() { CountryName = "Zimbabwe", DialCode = "+263" },
        };
    }
}